
import os
import sys

# Add parent directory to path to import _data
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from _data.lang import LANGUAGES, COMMON, INDEX_PAGE, SQL_FORMATTER, JSON_FORMATTER, BASE64_CONVERTER, PASSWORD_GENERATOR, UNIT_CONVERTER, DIFF_CHECKER, IMAGE_CONVERTER, QR_GENERATOR, COLOR_CONVERTER, LOREM_IPSUM, MARKDOWN_PREVIEWER, REGEX_TESTER, TEXT_UTILS, BMI_CALCULATOR, DATE_CALCULATOR, TIMER, IMAGE_WATERMARK, FAVICON_GENERATOR, THUMBNAIL_DOWNLOADER, REACTION_TEST, JWT_DECODER, HASH_GENERATOR, UNIX_TIMESTAMP, UUID_GENERATOR, URL_ENCODER, IMAGE_EDITOR, JPA_CONVERTER, JSON_TO_TS, EXCEL_TO_SQL, JSON_TO_EXCEL, JSON_LD_GENERATOR, PDF_TOOLS, TEXT_TO_DIAGRAM, ABOUT, PRIVACY, TERMS, NOT_FOUND

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, '_templates')

TOOLS_CONFIG = [
    ('image-watermark', '🛡️', IMAGE_WATERMARK),
    ('unit-converter', '📏', UNIT_CONVERTER),
    ('image-converter', '🖼️', IMAGE_CONVERTER),
    ('bmi-calculator', '⚖️', BMI_CALCULATOR),
    ('date-calculator', '📅', DATE_CALCULATOR),
    ('text-utils', '📝', TEXT_UTILS),
    ('json-formatter', '{ }', JSON_FORMATTER),
    ('color-converter', '🎨', COLOR_CONVERTER),
    ('timer', '⏱️', TIMER),
    ('base64-converter', '🔤', BASE64_CONVERTER),
    ('qr-generator', '📱', QR_GENERATOR),
    ('regex-tester', '🔍', REGEX_TESTER),
    ('sql-formatter', '🗄️', SQL_FORMATTER),
    ('lorem-ipsum', '📋', LOREM_IPSUM),
    ('favicon-generator', '🎯', FAVICON_GENERATOR),
    ('diff-checker', '🔀', DIFF_CHECKER),
    ('password-generator', '🔐', PASSWORD_GENERATOR),
    ('thumbnail-downloader', '📺', THUMBNAIL_DOWNLOADER),
    ('markdown-previewer', '📝', MARKDOWN_PREVIEWER),
    ('reaction-test', '⚡', REACTION_TEST),
    ('jwt-decoder', '🪪', JWT_DECODER),
    ('hash-generator', '🔑', HASH_GENERATOR),
    ('unix-timestamp', '⏲️', UNIX_TIMESTAMP),
    ('uuid-generator', '🆔', UUID_GENERATOR),
    ('url-encoder', '🔗', URL_ENCODER),
]

# Tools whose pages were authored by hand and live on disk (not generated by
# build_tool()). They are surfaced in the index, sitemap and inter-tool links
# but rendering of /<lang>/<tool>/index.html is handled by sync_prebuilt_tools().
PREBUILT_TOOLS = [
    ('image-editor', '🎨', IMAGE_EDITOR),
    ('jpa-converter', '🗃️', JPA_CONVERTER),
    ('json-to-ts', '🔁', JSON_TO_TS),
    ('excel-to-sql', '📊', EXCEL_TO_SQL),
    ('json-to-excel', '📈', JSON_TO_EXCEL),
    ('json-ld-generator', '🏷️', JSON_LD_GENERATOR),
    ('pdf-tools', '📄', PDF_TOOLS),
    ('text-to-diagram', '🧩', TEXT_TO_DIAGRAM),
]

ALL_TOOLS = TOOLS_CONFIG + PREBUILT_TOOLS

def load_template(template_name):
    path = os.path.join(TEMPLATE_DIR, template_name)
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        return inject_monetization(content)
    except FileNotFoundError:
        print(f"  WARN: template not found, skipping: {template_name}")
        return None


# --- Monetization injection ----------------------------------------------------
# Ezoic placeholder slot IDs used across all pages. Adding a div for a slot is
# sufficient — Ezoic delivers ads into whichever placeholders exist on the page.
EZOIC_SLOTS = (101, 103, 104)

import re as _re_ad


def _ad_div(n):
    return f'<div id="ezoic-pub-ad-placeholder-{n}"></div>'


def inject_monetization(html):
    """Strip duplicate AdSense scripts (Ezoic mediates AdSense itself) and
    insert Ezoic ad placeholder divs at standard positions, plus the
    showAds() trigger right before </body>.

    Idempotent: re-running on already-processed HTML is a no-op.
    """
    # 1. Remove direct AdSense loader if present (Ezoic + AdSense double-load
    #    is discouraged and frequently breaks ad fill). We strip both the
    #    comment header and the active/commented-out script tag in any order.
    html = _re_ad.sub(r'\s*<!--\s*Google AdSense[^\n]*-->\s*', '\n    ', html)
    html = _re_ad.sub(
        r'\s*<!--\s*<script\s+async\s+src="https://pagead2\.googlesyndication\.com[^"]*"[^>]*>\s*</script>\s*-->\s*',
        '\n    ', html,
    )
    html = _re_ad.sub(
        r'\s*<script\s+async\s+src="https://pagead2\.googlesyndication\.com[^"]*"[^>]*>\s*</script>\s*',
        '\n    ', html,
    )

    # 2. Insert ad placeholders if not yet present.
    if 'ezoic-pub-ad-placeholder-101' not in html:
        html = html.replace(
            '</header>',
            '</header>\n    ' + _ad_div(101),
            1,
        )
    if 'ezoic-pub-ad-placeholder-103' not in html and 'related-tools-section' in html:
        html = html.replace(
            '<div class="related-tools-section">',
            _ad_div(103) + '\n            <div class="related-tools-section">',
            1,
        )
    if 'ezoic-pub-ad-placeholder-104' not in html:
        html = html.replace(
            '</main>',
            '    ' + _ad_div(104) + '\n    </main>',
            1,
        )

    # 3. Trigger showAds() once per page (idempotent guard).
    if 'ezstandalone.showAds' not in html:
        slot_args = ','.join(str(s) for s in EZOIC_SLOTS)
        trigger = (
            '    <script>if(window.ezstandalone){ezstandalone.cmd.push(function(){'
            f'ezstandalone.showAds({slot_args});'
            '});}</script>\n'
        )
        html = html.replace('</body>', trigger + '</body>', 1)

    # 4. Inject legal-page links into footer of *templates* (those still have
    #    the {{ lang_code }} placeholder). For prebuilt hand-authored pages we
    #    inject lang-resolved links separately in sync_prebuilt_tools().
    if '{{ lang_code }}' in html and 'data-legal-links' not in html:
        legal_block = (
            '\n                <p data-legal-links style="font-size: 0.875rem; margin-top: 8px;">'
            '<a href="/{{ lang_code }}/about/">{{ link_about }}</a> · '
            '<a href="/{{ lang_code }}/privacy/">{{ link_privacy }}</a> · '
            '<a href="/{{ lang_code }}/terms/">{{ link_terms }}</a>'
            '</p>'
        )
        html = _re_ad.sub(
            r'(<p>\{\{ footer \}\}</p>)',
            r'\1' + legal_block,
            html, count=1,
        )

    return html


def inject_legal_links_resolved(html, lang):
    """Insert legal-page footer links with the language code already
    substituted. Used for prebuilt pages that arrive at sync time without
    {{ lang_code }} placeholders. Idempotent."""
    if 'data-legal-links' in html:
        return html
    common = COMMON.get('en', {}).copy()
    common.update(COMMON.get(lang, {}))
    about = common.get('link_about', 'About')
    privacy = common.get('link_privacy', 'Privacy')
    terms = common.get('link_terms', 'Terms')
    block = (
        f'\n                <p data-legal-links style="font-size: 0.875rem; margin-top: 8px;">'
        f'<a href="/{lang}/about/">{about}</a> · '
        f'<a href="/{lang}/privacy/">{privacy}</a> · '
        f'<a href="/{lang}/terms/">{terms}</a>'
        f'</p>'
    )
    # Insert before </footer>'s inner closing div.
    out = _re_ad.sub(
        r'(</div>\s*</div>\s*</footer>)',
        block + r'\n            \1',
        html, count=1,
    )
    return out
# --- end monetization ----------------------------------------------------------

def build_index_page():
    print("Building index pages...")
    template = load_template('index.html')
    
    for lang in LANGUAGES:
        # Prepare data: English fallback for any missing sub-keys
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(INDEX_PAGE.get('en', {}))
        data.update(INDEX_PAGE.get(lang, {}))
        data['lang_code'] = lang
        
        # Generate alternate links
        alt_links = []
        for l in LANGUAGES:
            if l == 'zh-cn':
                hreflang = 'zh-Hans'
            elif l == 'zh-tw':
                hreflang = 'zh-Hant'
            else:
                hreflang = l
            alt_links.append(f'<link rel="alternate" hreflang="{hreflang}" href="https://utilifyapp.net/{l}/">')
            
        alt_links.append('<link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/">')
        data['alternate_links'] = '\n  '.join(alt_links)

        # Generate tool cards
        cards_html = []
        for tool_path, icon, tool_dict in ALL_TOOLS:
            t_data = tool_dict.get(lang, tool_dict.get('en', {}))
            title = t_data.get('title', tool_dict.get('en', {}).get('title', ''))
            
            # Try page_desc first, then meta_desc
            desc = t_data.get('page_desc', t_data.get('meta_desc', ''))
            
            # Fallback to English if missing
            if not title:
                title = tool_dict['en']['title']
            if not desc:
                desc = tool_dict['en'].get('page_desc', tool_dict['en'].get('meta_desc', ''))

            card = f'''
        <a href="/{lang}/{tool_path}/" class="card">
          <div class="card-icon">{icon}</div>
          <h3 class="card-title">{title}</h3>
          <p class="card-description">{desc}</p>
        </a>'''
            cards_html.append(card)
        
        data['tool_cards'] = '\n'.join(cards_html)
        
        # Replace placeholders
        content = template
        for key, value in data.items():
             content = content.replace(f'{{{{ {key} }}}}', str(value))
             
        # Write
        output_dir = os.path.join(BASE_DIR, lang)
        os.makedirs(output_dir, exist_ok=True)
        with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"  Generated {lang}/index.html")

def build_conversion_pages():
    """Programmatic SEO: render `_templates/convert_pair.html` for every
    (pair × language) combination, producing /<lang>/convert/<from>-to-<to>/."""
    print("Building conversion pages...")
    template = load_template('convert_pair.html')
    if template is None:
        return

    from _data.conversions import (
        CONVERSION_PAIRS, TABLE_INPUT_VALUES, TABLE_INPUT_VALUES_TEMP,
        convert as py_convert, format_number,
    )
    import json as _json

    same_type = {}
    for p in CONVERSION_PAIRS:
        same_type.setdefault(p['type'], []).append(p)

    for pair in CONVERSION_PAIRS:
        slug = f"{pair['from']}-to-{pair['to']}"
        url_path = f"convert/{slug}"
        alt_links_html = build_alt_links(url_path)

        is_temp = pair['type'] == 'temperature'
        inputs = TABLE_INPUT_VALUES_TEMP if is_temp else TABLE_INPUT_VALUES

        # Pre-compute table at build time for SEO content.
        table_rows = []
        for v in inputs:
            result = py_convert(v, pair['mode'], pair.get('factor'))
            table_rows.append(
                f"<tr><td>{format_number(v, 0)}</td>"
                f"<td>{format_number(result, pair['precision'])}</td></tr>"
            )
        table_rows_html = '\n                    '.join(table_rows)

        for lang in LANGUAGES:
            data = COMMON.get('en', {}).copy()
            data.update(COMMON.get(lang, {}))
            data['lang_code'] = lang
            data['pair_slug'] = slug
            data['alternate_links'] = alt_links_html

            from_long = pair['from_long'].get(lang, pair['from_long']['en'])
            to_long = pair['to_long'].get(lang, pair['to_long']['en'])

            if lang == 'ko':
                data['h1_text'] = f"{from_long} → {to_long} 변환기"
                data['intro_text'] = (
                    f"{from_long}({pair['from']})를 {to_long}({pair['to']})로 빠르게 변환하세요. "
                    f"입력값은 브라우저에서만 처리됩니다."
                )
                data['formula_label'] = "공식:"
                data['table_title'] = "변환 표"
                data['faq_title'] = "자주 묻는 질문"
                data['related_header'] = "관련 도구"
                data['related_main'] = "전체 단위 변환기"
                data['meta_title'] = f"{from_long} → {to_long} 변환기 - Utilify"
                data['meta_desc'] = (
                    f"{pair['from']}를 {pair['to']}로 변환하는 무료 온라인 도구. "
                    f"공식, 변환 표, 즉시 계산. 모든 처리는 브라우저에서 수행됩니다."
                )
            else:
                data['h1_text'] = f"{from_long.title()} to {to_long.title()} Converter"
                data['intro_text'] = (
                    f"Convert {from_long} ({pair['from']}) to {to_long} ({pair['to']}) instantly. "
                    f"All calculations run in your browser."
                )
                data['formula_label'] = "Formula:"
                data['table_title'] = "Conversion Table"
                data['faq_title'] = "Frequently Asked Questions"
                data['related_header'] = "Related Tools"
                data['related_main'] = "Full Unit Converter"
                data['meta_title'] = f"{from_long.title()} to {to_long.title()} Converter (Free Online) - Utilify"
                data['meta_desc'] = (
                    f"Convert {pair['from']} to {pair['to']} online — free, no signup, no upload. "
                    f"Formula, conversion table, instant results. {pair['formula']}."
                )

            data['from_long'] = from_long.title() if lang != 'ko' else from_long
            data['to_long'] = to_long.title() if lang != 'ko' else to_long
            data['formula'] = pair['formula']
            data['mode'] = pair['mode']
            data['factor_js'] = repr(pair.get('factor', 0)) if pair['mode'] == 'linear' else '0'
            data['precision'] = pair['precision']
            data['table_rows_html'] = table_rows_html

            # FAQ content (en/ko only; others fall back to en).
            one_to_target = py_convert(1, pair['mode'], pair.get('factor'))
            one_to_target_str = format_number(one_to_target, pair['precision'])
            ten_to_target_str = format_number(py_convert(10, pair['mode'], pair.get('factor')), pair['precision'])

            if lang == 'ko':
                faqs = [
                    (
                        f"1 {pair['from']}는 몇 {pair['to']}인가요?",
                        f"1 {pair['from']} = {one_to_target_str} {pair['to']} 입니다. {pair['formula']}",
                    ),
                    (
                        f"{pair['from']}를 {pair['to']}로 변환하는 공식은?",
                        f"{pair['formula']}. 역변환: {pair['inverse_formula']}.",
                    ),
                    (
                        f"10 {pair['from']}는 몇 {pair['to']}인가요?",
                        f"10 {pair['from']} = {ten_to_target_str} {pair['to']} 입니다.",
                    ),
                    (
                        f"이 변환은 정확한가요?",
                        f"네, 표준 정의에 따른 정확한 변환 계수를 사용합니다 (소수점 {pair['precision']}자리까지 표시).",
                    ),
                ]
            else:
                faqs = [
                    (
                        f"How many {pair['to']} are in 1 {pair['from']}?",
                        f"1 {pair['from']} equals {one_to_target_str} {pair['to']}. {pair['formula']}",
                    ),
                    (
                        f"What is the formula to convert {pair['from']} to {pair['to']}?",
                        f"{pair['formula']}. Inverse: {pair['inverse_formula']}.",
                    ),
                    (
                        f"How many {pair['to']} are in 10 {pair['from']}?",
                        f"10 {pair['from']} equals {ten_to_target_str} {pair['to']}.",
                    ),
                    (
                        f"Is this conversion exact?",
                        f"Yes, the converter uses the standard definition factor and rounds the displayed result to {pair['precision']} decimal places.",
                    ),
                ]

            faq_html_parts = [
                f'<details class="faq" open><summary>{q}</summary><p>{a}</p></details>'
                for q, a in faqs
            ]
            data['faq_html'] = '\n            '.join(faq_html_parts)

            faq_jsonld = {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {"@type": "Question", "name": q,
                     "acceptedAnswer": {"@type": "Answer", "text": a}}
                    for q, a in faqs
                ],
            }
            data['faq_jsonld'] = _json.dumps(faq_jsonld, ensure_ascii=False, indent=2)

            related = []
            for other in same_type[pair['type']]:
                if other is pair:
                    continue
                other_from = other['from_long'].get(lang, other['from_long']['en'])
                other_to = other['to_long'].get(lang, other['to_long']['en'])
                arrow = " → "
                related.append(
                    f'<a href="/{lang}/convert/{other["from"]}-to-{other["to"]}/" class="related-btn">'
                    f'{other_from.title() if lang != "ko" else other_from}{arrow}'
                    f'{other_to.title() if lang != "ko" else other_to}</a>'
                )
            data['related_pairs_html'] = ''.join(related)

            content = template
            for key, value in data.items():
                content = content.replace(f'{{{{ {key} }}}}', str(value))

            output_dir = os.path.join(BASE_DIR, lang, 'convert', slug)
            os.makedirs(output_dir, exist_ok=True)
            with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
                f.write(content)
        print(f"  Generated convert/{slug}/ for {len(LANGUAGES)} languages")


def build_static_page(slug, page_data, root_404=False):
    """Render `_templates/static_page.html` for each language to /<lang>/<slug>/.
    If root_404 is True, also write the English version to /404.html so GitHub
    Pages serves it for unknown URLs."""
    print(f"Building static page: {slug}...")
    template = load_template('static_page.html')
    if template is None:
        return

    alt_links_html = build_alt_links(slug)

    for lang in LANGUAGES:
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(page_data.get('en', {}))
        data.update(page_data.get(lang, {}))
        data['lang_code'] = lang
        data['page_slug'] = slug
        data['alternate_links'] = alt_links_html

        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))

        output_dir = os.path.join(BASE_DIR, lang, slug)
        os.makedirs(output_dir, exist_ok=True)
        with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  Generated {lang}/{slug}/index.html")

    if root_404:
        # Render an English copy at /404.html so GitHub Pages serves it on misses.
        data = COMMON.get('en', {}).copy()
        data.update(page_data.get('en', {}))
        data['lang_code'] = 'en'
        data['page_slug'] = slug
        data['alternate_links'] = alt_links_html
        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))
        with open(os.path.join(BASE_DIR, '404.html'), 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  Generated /404.html")


def build_alt_links(tool_path):
    alt = []
    for l in LANGUAGES:
        if l == 'zh-cn':
            hreflang = 'zh-Hans'
        elif l == 'zh-tw':
            hreflang = 'zh-Hant'
        else:
            hreflang = l
        alt.append(f'<link rel="alternate" hreflang="{hreflang}" href="https://utilifyapp.net/{l}/{tool_path}/">')
    alt.append(f'<link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/{tool_path}/">')
    return '\n    '.join(alt)


def build_tool(tool_name, tool_data, template_file):
    print(f"Building {tool_name}...")
    template = load_template(template_file)
    if template is None:
        return

    alt_links_html = build_alt_links(tool_name)

    for lang in LANGUAGES:
        # Merge common and specific data with English as fallback for missing sub-keys
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(tool_data.get('en', {}))
        data.update(tool_data.get(lang, {}))
        data['lang_code'] = lang
        data['alternate_links'] = alt_links_html

        # Replace placeholders
        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))
            
        # Write to file
        output_dir = os.path.join(BASE_DIR, lang, tool_name)
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, 'index.html')
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"  Generated {lang}/{tool_name}/index.html")


def hreflang_for(lang):
    if lang == 'zh-cn':
        return 'zh-Hans'
    if lang == 'zh-tw':
        return 'zh-Hant'
    return lang


def build_sitemap(today=None):
    print("Building sitemap.xml...")
    from datetime import date
    lastmod = (today or date.today()).isoformat()

    paths = ['']  # root
    paths += [f'{l}/' for l in LANGUAGES]
    for tool_path, _icon, _data in ALL_TOOLS:
        for l in LANGUAGES:
            paths.append(f'{l}/{tool_path}/')

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
             '        xmlns:xhtml="http://www.w3.org/1999/xhtml">']

    def emit(loc, alternates=None):
        lines.append('  <url>')
        lines.append(f'    <loc>{loc}</loc>')
        lines.append(f'    <lastmod>{lastmod}</lastmod>')
        if alternates:
            for hl, href in alternates:
                lines.append(f'    <xhtml:link rel="alternate" hreflang="{hl}" href="{href}"/>')
        lines.append('  </url>')

    # Root
    emit('https://utilifyapp.net/')

    # Language home pages with hreflang siblings
    home_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/') for l in LANGUAGES]
    home_alts.append(('x-default', 'https://utilifyapp.net/en/'))
    for l in LANGUAGES:
        emit(f'https://utilifyapp.net/{l}/', home_alts)

    # Tool pages with hreflang siblings
    for tool_path, _icon, _data in ALL_TOOLS:
        tool_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{tool_path}/') for l in LANGUAGES]
        tool_alts.append(('x-default', f'https://utilifyapp.net/en/{tool_path}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{tool_path}/', tool_alts)

    # Static / legal pages
    for slug in STATIC_PAGE_SLUGS:
        slug_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{slug}/') for l in LANGUAGES]
        slug_alts.append(('x-default', f'https://utilifyapp.net/en/{slug}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{slug}/', slug_alts)
        paths.extend([f'{l}/{slug}/' for l in LANGUAGES])

    # Programmatic SEO conversion pairs
    try:
        from _data.conversions import CONVERSION_PAIRS
    except ImportError:
        CONVERSION_PAIRS = []
    for pair in CONVERSION_PAIRS:
        slug = f"convert/{pair['from']}-to-{pair['to']}"
        pair_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{slug}/') for l in LANGUAGES]
        pair_alts.append(('x-default', f'https://utilifyapp.net/en/{slug}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{slug}/', pair_alts)
        paths.extend([f'{l}/{slug}/' for l in LANGUAGES])

    lines.append('</urlset>')
    out = os.path.join(BASE_DIR, 'sitemap.xml')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Generated sitemap.xml ({len(paths)} urls)")


STATIC_PAGE_SLUGS = ['about', 'privacy', 'terms']


PREBUILT_LANGS_AUTHORED = ['en', 'ko', 'ja', 'de', 'hi', 'id', 'pt', 'th', 'vi']
PREBUILT_LANGS_CLONED = ['zh-cn', 'zh-tw']

# Block of <link rel="alternate" ...> entries for hand-authored prebuilt tool
# pages. We replace whatever the page currently has between the "<!-- Language
# Alternatives -->" marker and the next blank line, so old 9-language blocks
# get refreshed to include zh-cn / zh-tw.
import re as _re


def _build_prebuilt_alternates(tool_path: str) -> str:
    lines = ['  <!-- Language Alternatives -->']
    for l in LANGUAGES:
        hl = hreflang_for(l)
        lines.append(f'  <link rel="alternate" hreflang="{hl}" href="https://utilifyapp.net/{l}/{tool_path}/">')
    lines.append(f'  <link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/{tool_path}/">')
    return '\n'.join(lines)


def _refresh_alternates(html: str, tool_path: str) -> str:
    block = _build_prebuilt_alternates(tool_path)
    pattern = _re.compile(
        r'[ \t]*<!--\s*Language Alternatives\s*-->\s*\n'
        r'(?:[ \t]*<link\s+rel="alternate"[^>]*>\s*\n)+',
        _re.IGNORECASE,
    )
    if pattern.search(html):
        return pattern.sub(block + '\n', html, count=1)
    # No existing block — insert before </head>.
    return html.replace('</head>', block + '\n</head>', 1)


def _retarget_lang(html: str, tool_path: str, dst_lang: str) -> str:
    """Convert an English-locale HTML page into another locale by rewriting
    the `lang` attribute, JSON-LD `inLanguage`, and the canonical/og:url for
    /en/<tool>/. Only the *self* URL is rewritten — alternate links are
    regenerated separately via _refresh_alternates."""
    out = html.replace('<html lang="en">', f'<html lang="{dst_lang}">', 1)
    out = out.replace('"inLanguage": "en"', f'"inLanguage": "{dst_lang}"')
    out = out.replace(
        f'href="https://utilifyapp.net/en/{tool_path}/"',
        f'href="https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    out = out.replace(
        f'content="https://utilifyapp.net/en/{tool_path}/"',
        f'content="https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    out = out.replace(
        f'"url": "https://utilifyapp.net/en/{tool_path}/"',
        f'"url": "https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    # Header logo link.
    out = out.replace(f'href="/en/"', f'href="/{dst_lang}/"')
    return out


def sync_prebuilt_tools():
    print("Syncing prebuilt tool pages (hreflang refresh + zh-cn/zh-tw clones)...")
    for tool_path, _icon, _tool_dict in PREBUILT_TOOLS:
        # Refresh authored language pages so they include zh-cn / zh-tw alternates.
        for lang in PREBUILT_LANGS_AUTHORED:
            page = os.path.join(BASE_DIR, lang, tool_path, 'index.html')
            if not os.path.exists(page):
                continue
            with open(page, 'r', encoding='utf-8') as f:
                content = f.read()
            new_content = _refresh_alternates(content, tool_path)
            new_content = inject_monetization(new_content)
            new_content = inject_legal_links_resolved(new_content, lang)
            if new_content != content:
                with open(page, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"  refreshed {lang}/{tool_path}/index.html")

        # Clone the English page into zh-cn / zh-tw so those locales link to a
        # page rather than 404. The clone is a one-shot fallback — we only
        # write it if no page exists, so a future hand-translated version is
        # not overwritten.
        en_page = os.path.join(BASE_DIR, 'en', tool_path, 'index.html')
        if not os.path.exists(en_page):
            print(f"  WARN: missing en/{tool_path}/index.html, skipping clones")
            continue
        with open(en_page, 'r', encoding='utf-8') as f:
            en_content = f.read()
        for clone_lang in PREBUILT_LANGS_CLONED:
            clone_dir = os.path.join(BASE_DIR, clone_lang, tool_path)
            clone_path = os.path.join(clone_dir, 'index.html')
            if os.path.exists(clone_path):
                # Existing clone: still refresh hreflang + monetization so prior
                # builds don't keep stale AdSense scripts.
                with open(clone_path, 'r', encoding='utf-8') as f:
                    existing = f.read()
                refreshed = _refresh_alternates(existing, tool_path)
                refreshed = inject_monetization(refreshed)
                refreshed = inject_legal_links_resolved(refreshed, clone_lang)
                if refreshed != existing:
                    with open(clone_path, 'w', encoding='utf-8') as f:
                        f.write(refreshed)
                    print(f"  refreshed clone {clone_lang}/{tool_path}/index.html")
                continue
            retargeted = _retarget_lang(en_content, tool_path, clone_lang)
            retargeted = _refresh_alternates(retargeted, tool_path)
            retargeted = inject_monetization(retargeted)
            retargeted = inject_legal_links_resolved(retargeted, clone_lang)
            os.makedirs(clone_dir, exist_ok=True)
            with open(clone_path, 'w', encoding='utf-8') as f:
                f.write(retargeted)
            print(f"  cloned en/{tool_path}/ → {clone_lang}/{tool_path}/")


if __name__ == '__main__':
    # Build Index Pages
    build_index_page()

    # Build Tool Pages
    build_tool('sql-formatter', SQL_FORMATTER, 'sql-formatter.html')
    build_tool('json-formatter', JSON_FORMATTER, 'json-formatter.html')
    build_tool('base64-converter', BASE64_CONVERTER, 'base64-converter.html')
    build_tool('password-generator', PASSWORD_GENERATOR, 'password-generator.html')
    build_tool('unit-converter', UNIT_CONVERTER, 'unit-converter.html')
    build_tool('diff-checker', DIFF_CHECKER, 'diff-checker.html')
    build_tool('image-converter', IMAGE_CONVERTER, 'image-converter.html')
    build_tool('qr-generator', QR_GENERATOR, 'qr-generator.html')
    build_tool('color-converter', COLOR_CONVERTER, 'color-converter.html')
    build_tool('lorem-ipsum', LOREM_IPSUM, 'lorem-ipsum.html')
    build_tool('markdown-previewer', MARKDOWN_PREVIEWER, 'markdown-previewer.html')
    build_tool('regex-tester', REGEX_TESTER, 'regex-tester.html')
    build_tool('text-utils', TEXT_UTILS, 'text-utils.html')
    build_tool('bmi-calculator', BMI_CALCULATOR, 'bmi-calculator.html')
    build_tool('date-calculator', DATE_CALCULATOR, 'date-calculator.html')
    build_tool('timer', TIMER, 'timer.html')
    build_tool('image-watermark', IMAGE_WATERMARK, 'image-watermark.html')
    build_tool('favicon-generator', FAVICON_GENERATOR, 'favicon-generator.html')
    build_tool('thumbnail-downloader', THUMBNAIL_DOWNLOADER, 'thumbnail-downloader.html')
    build_tool('reaction-test', REACTION_TEST, 'reaction-test.html')
    build_tool('jwt-decoder', JWT_DECODER, 'jwt-decoder.html')
    build_tool('hash-generator', HASH_GENERATOR, 'hash-generator.html')
    build_tool('unix-timestamp', UNIX_TIMESTAMP, 'unix-timestamp.html')
    build_tool('uuid-generator', UUID_GENERATOR, 'uuid-generator.html')
    build_tool('url-encoder', URL_ENCODER, 'url-encoder.html')

    # Static / legal / 404 pages.
    build_static_page('about', ABOUT)
    build_static_page('privacy', PRIVACY)
    build_static_page('terms', TERMS)
    build_static_page('404', NOT_FOUND, root_404=True)

    # Programmatic SEO conversion pages.
    build_conversion_pages()

    # Sync hand-authored prebuilt tools (refresh hreflang block, clone to zh-cn/zh-tw).
    sync_prebuilt_tools()

    # Build sitemap.xml
    build_sitemap()

    print("Build complete!")
