
import os
import sys

# Add parent directory to path to import _data
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from _data.lang import LANGUAGES, COMMON, INDEX_PAGE, SQL_FORMATTER, JSON_FORMATTER, BASE64_CONVERTER, PASSWORD_GENERATOR, UNIT_CONVERTER, DIFF_CHECKER, IMAGE_CONVERTER, QR_GENERATOR, COLOR_CONVERTER, LOREM_IPSUM, MARKDOWN_PREVIEWER, REGEX_TESTER, TEXT_UTILS, BMI_CALCULATOR, DATE_CALCULATOR, TIMER, IMAGE_WATERMARK, FAVICON_GENERATOR, THUMBNAIL_DOWNLOADER, REACTION_TEST, JWT_DECODER, HASH_GENERATOR, UNIX_TIMESTAMP, UUID_GENERATOR, URL_ENCODER, IMAGE_EDITOR, JPA_CONVERTER, JSON_TO_TS, EXCEL_TO_SQL, JSON_TO_EXCEL, JSON_LD_GENERATOR, PDF_TOOLS, TEXT_TO_DIAGRAM, ABOUT, PRIVACY, TERMS, NOT_FOUND, PROMPT_PII_SCRUBBER, CLAUDE_MD_GEN, MCP_CONFIG_GEN, TOKEN_COUNTER, AI_IMAGE_INSPECTOR, CHATGPT_TO_BLOG, LOAN_CALCULATOR, COMPOUND_INTEREST, RETIREMENT_CALCULATOR, CALORIE_CALCULATOR, PREGNANCY_CALCULATOR, BODY_FAT_CALCULATOR, FINANCE_HUB, HEALTH_HUB, RAG_CHUNKER, FEW_SHOT_FORMATTER, JSON_SCHEMA_VALIDATOR, TIP_CALCULATOR, PERCENTAGE_CALCULATOR, DISCOUNT_CALCULATOR

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, '_templates')

TOOLS_CONFIG = [
    ('image-watermark', '🛡️', IMAGE_WATERMARK),
    ('unit-converter', '📏', UNIT_CONVERTER),
    ('image-converter', '🖼️', IMAGE_CONVERTER),
    ('bmi-calculator', '⚖️', BMI_CALCULATOR),
    ('date-calculator', '📅', DATE_CALCULATOR),
    ('text-utils', '📝', TEXT_UTILS),
    ('json-formatter', '{ }', JSON_FORMATTER),
    ('color-converter', '🎨', COLOR_CONVERTER),
    ('timer', '⏱️', TIMER),
    ('base64-converter', '🔤', BASE64_CONVERTER),
    ('qr-generator', '📱', QR_GENERATOR),
    ('regex-tester', '🔍', REGEX_TESTER),
    ('sql-formatter', '🗄️', SQL_FORMATTER),
    ('lorem-ipsum', '📋', LOREM_IPSUM),
    ('favicon-generator', '🎯', FAVICON_GENERATOR),
    ('diff-checker', '🔀', DIFF_CHECKER),
    ('password-generator', '🔐', PASSWORD_GENERATOR),
    ('thumbnail-downloader', '📺', THUMBNAIL_DOWNLOADER),
    ('markdown-previewer', '📝', MARKDOWN_PREVIEWER),
    ('reaction-test', '⚡', REACTION_TEST),
    ('jwt-decoder', '🪪', JWT_DECODER),
    ('hash-generator', '🔑', HASH_GENERATOR),
    ('unix-timestamp', '⏲️', UNIX_TIMESTAMP),
    ('uuid-generator', '🆔', UUID_GENERATOR),
    ('url-encoder', '🔗', URL_ENCODER),
    # AI-era utilities
    ('token-counter', '🪙', TOKEN_COUNTER),
    ('mcp-config-generator', '🔌', MCP_CONFIG_GEN),
    ('ai-image-inspector', '🔬', AI_IMAGE_INSPECTOR),
    ('chatgpt-to-blog', '📝', CHATGPT_TO_BLOG),
    ('prompt-pii-scrubber', '🛡️', PROMPT_PII_SCRUBBER),
    ('claude-md-generator', '📜', CLAUDE_MD_GEN),
    # Finance calculators
    ('loan-calculator', '💰', LOAN_CALCULATOR),
    ('compound-interest', '📈', COMPOUND_INTEREST),
    ('retirement-calculator', '🏖️', RETIREMENT_CALCULATOR),
    # Health calculators
    ('calorie-calculator', '🔥', CALORIE_CALCULATOR),
    ('pregnancy-calculator', '🤰', PREGNANCY_CALCULATOR),
    ('body-fat-calculator', '💪', BODY_FAT_CALCULATOR),
    # AI / prompt-engineering tools (Tier 3)
    ('rag-chunker', '✂️', RAG_CHUNKER),
    ('few-shot-formatter', '🎯', FEW_SHOT_FORMATTER),
    ('json-schema-validator', '🛡️', JSON_SCHEMA_VALIDATOR),
    # General-purpose calculators (high search volume)
    ('tip-calculator', '💵', TIP_CALCULATOR),
    ('percentage-calculator', '％', PERCENTAGE_CALCULATOR),
    ('discount-calculator', '🏷️', DISCOUNT_CALCULATOR),
]

# Tools whose pages were authored by hand and live on disk (not generated by
# build_tool()). They are surfaced in the index, sitemap and inter-tool links
# but rendering of /<lang>/<tool>/index.html is handled by sync_prebuilt_tools().
PREBUILT_TOOLS = [
    ('image-editor', '🎨', IMAGE_EDITOR),
    ('jpa-converter', '🗃️', JPA_CONVERTER),
    ('json-to-ts', '🔁', JSON_TO_TS),
    ('excel-to-sql', '📊', EXCEL_TO_SQL),
    ('json-to-excel', '📈', JSON_TO_EXCEL),
    ('json-ld-generator', '🏷️', JSON_LD_GENERATOR),
    ('pdf-tools', '📄', PDF_TOOLS),
    ('text-to-diagram', '🧩', TEXT_TO_DIAGRAM),
]

ALL_TOOLS = TOOLS_CONFIG + PREBUILT_TOOLS

def load_template(template_name):
    path = os.path.join(TEMPLATE_DIR, template_name)
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        return inject_monetization(content)
    except FileNotFoundError:
        print(f"  WARN: template not found, skipping: {template_name}")
        return None


# --- Monetization injection ----------------------------------------------------
# Site is monetized via Google AdSense Auto Ads. We inject a single AdSense
# loader script in <head> and a single Auto Ads enable trigger before </body>.
# Auto Ads chooses placement automatically — no per-slot divs or slot IDs.
# Funding Choices CMP for EU/UK consent is added by the user separately.
ADSENSE_CLIENT = "ca-pub-6334819180242631"

import re as _re_ad


def inject_monetization(html):
    """Idempotently strip Ezoic remnants (CMP/sa.min.js/analytics/ezstandalone
    bootstrap, ad placeholder divs, showAds trigger) and inject the AdSense
    loader + Auto Ads trigger. Also injects legal footer links.
    """
    # 1. Strip Ezoic CMP scripts (both gatekeeperconsent endpoints).
    html = _re_ad.sub(
        r'\s*<script[^>]*\bsrc="https://(?:cmp|the)\.gatekeeperconsent\.com/[^"]*"[^>]*></script>\s*',
        '\n    ', html,
    )
    # 2. Strip Ezoic SA loader.
    html = _re_ad.sub(
        r'\s*<script[^>]*\bsrc="https://www\.ezojs\.com/ezoic/sa\.min\.js"[^>]*></script>\s*',
        '\n    ', html,
    )
    # 3. Strip Ezoic analytics loader.
    html = _re_ad.sub(
        r'\s*<script[^>]*\bsrc="https://ezoicanalytics\.com/[^"]*"[^>]*></script>\s*',
        '\n    ', html,
    )
    # 4. Strip the inline ezstandalone bootstrap block.
    html = _re_ad.sub(
        r'\s*<script>\s*window\.ezstandalone\s*=[\s\S]*?ezstandalone\.cmd\s*=[\s\S]*?</script>\s*',
        '\n    ', html,
    )
    # 5. Strip the "<!-- Ezoic -->" comment header.
    html = _re_ad.sub(r'\s*<!--\s*Ezoic\s*-->\s*', '\n    ', html)
    # 6. Strip any leftover ezoic-pub-ad-placeholder divs.
    html = _re_ad.sub(
        r'\s*<div\s+id="ezoic-pub-ad-placeholder-\d+"></div>\s*',
        '\n    ', html,
    )
    # 7. Strip the ezstandalone.showAds() trigger.
    html = _re_ad.sub(
        r'\s*<script>[^<]*ezstandalone\.showAds\([^)]*\);[^<]*</script>\s*',
        '\n', html,
    )

    # 7b. Strip legacy commented-out AdSense loader blocks left over from
    #     prior cleanup ("<!-- Google AdSense Removed for Developer Experience -->"
    #     followed by a commented-out script tag). Otherwise their substring
    #     match would defeat the idempotency check below and we'd skip
    #     injecting the live loader.
    html = _re_ad.sub(
        r'\s*<!--\s*Google AdSense[^-]*-->\s*\n?'
        r'(?:\s*<!--\s*Google AdSense Removed[^-]*-->\s*\n?)?'
        r'(?:\s*<!--\s*<script\s+async\s+src="https://pagead2\.googlesyndication\.com[^>]*>\s*</script>\s*-->\s*\n?)?',
        '\n    ', html,
    )

    # 8. Inject the AdSense loader once in <head>. Use a *unique* marker
    #    string in the inserted comment so the idempotency check is robust
    #    against random substrings in the page.
    if 'data-utilify-adsense-loader' not in html:
        loader = (
            '    <script data-utilify-adsense-loader async '
            f'src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={ADSENSE_CLIENT}" '
            'crossorigin="anonymous"></script>\n'
        )
        html = html.replace('</head>', loader + '</head>', 1)

    # 9. Inject the Auto Ads enable trigger once before </body>.
    if 'enable_page_level_ads' not in html:
        trigger = (
            '    <script>(adsbygoogle=window.adsbygoogle||[]).push({'
            f'google_ad_client:"{ADSENSE_CLIENT}",enable_page_level_ads:true'
            '});</script>\n'
        )
        html = html.replace('</body>', trigger + '</body>', 1)

    # 9b. Inject OG image + Twitter card meta once in <head>. Marker
    #     `data-utilify-og` guards idempotency against re-runs.
    if 'data-utilify-og' not in html:
        og_block = (
            '    <meta data-utilify-og property="og:image" content="https://utilifyapp.net/assets/og-image.png">\n'
            '    <meta property="og:image:width" content="1200">\n'
            '    <meta property="og:image:height" content="630">\n'
            '    <meta property="og:site_name" content="Utilify">\n'
            '    <meta name="twitter:card" content="summary_large_image">\n'
            '    <meta name="twitter:image" content="https://utilifyapp.net/assets/og-image.png">\n'
        )
        html = html.replace('</head>', og_block + '</head>', 1)

    # 9d. Inject favicon links once in <head>. Marker `data-utilify-favicon`
    #     guards idempotency. Browsers auto-request /favicon.ico anyway, but
    #     advertising the multi-size set yields a sharper tab/bookmark icon
    #     and gives Apple/Android proper home-screen icons.
    if 'data-utilify-favicon' not in html:
        favicon_block = (
            '    <link data-utilify-favicon rel="icon" type="image/x-icon" href="/favicon.ico">\n'
            '    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n'
            '    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n'
            '    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n'
        )
        html = html.replace('</head>', favicon_block + '</head>', 1)

    # 9f. Dark-mode init: read localStorage 'utilify_theme' (or
    #     prefers-color-scheme as fallback) and set `data-theme` on <html>
    #     before paint. Inlined and synchronous — runs as the first thing
    #     in <head> after meta charset, so the body never renders in the
    #     wrong theme.
    if 'data-utilify-theme-init' not in html:
        theme_init = (
            '    <script data-utilify-theme-init>(function(){try{'
            'var s=localStorage.getItem("utilify_theme");'
            'var t=(s==="dark"||s==="light")?s:'
            '(window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");'
            'document.documentElement.setAttribute("data-theme",t);'
            '}catch(e){}})();</script>\n'
        )
        html = html.replace('</head>', theme_init + '</head>', 1)

    # 9g. Inject the theme-toggle button next to the site logo + the click
    #     handler before </body>. The button uses {{ theme_toggle_aria }}
    #     for its aria-label; the placeholder resolves at template-fill time
    #     for `{{ lang_code }}` templates and is replaced inline for prebuilt
    #     pages with their resolved language string.
    if 'data-utilify-theme-toggle' not in html:
        is_template = '{{ lang_code }}' in html
        if is_template:
            aria_label = '{{ theme_toggle_aria }}'
        else:
            # Detect language from <html lang="..."> for prebuilt pages.
            lang_match = _re_ad.search(r'<html[^>]+lang="([^"]+)"', html)
            lang_code = lang_match.group(1) if lang_match else 'en'
            common_en = COMMON.get('en', {})
            common_lang = COMMON.get(lang_code, {})
            aria_label = (common_lang.get('theme_toggle_aria')
                          or common_en.get('theme_toggle_aria')
                          or 'Toggle dark mode')
        toggle_btn = (
            f'<button data-utilify-theme-toggle id="themeToggle" '
            f'class="theme-toggle" aria-label="{aria_label}" type="button">🌙</button>'
        )
        # Insert immediately after the logo's closing </a> tag.
        html = _re_ad.sub(
            r'(<a\s+href="[^"]+"\s+class="site-logo"[^>]*>[^<]*</a>)',
            r'\1' + toggle_btn,
            html, count=1,
        )
        # Append handler before </body>.
        toggle_handler = (
            '    <script data-utilify-theme-toggle-script>(function(){'
            'var b=document.getElementById("themeToggle");if(!b)return;'
            'function p(){var t=document.documentElement.getAttribute("data-theme")||"light";'
            'b.textContent=t==="dark"?"☀️":"🌙";'
            'b.setAttribute("aria-pressed",String(t==="dark"));}'
            'p();b.addEventListener("click",function(){'
            'var c=document.documentElement.getAttribute("data-theme")||"light";'
            'var n=c==="dark"?"light":"dark";'
            'document.documentElement.setAttribute("data-theme",n);'
            'try{localStorage.setItem("utilify_theme",n);}catch(e){}p();});'
            '})();</script>\n'
        )
        html = html.replace('</body>', toggle_handler + '</body>', 1)

    # 9e. Inject favorites star toggle into tool-page security-badge row, plus
    #     the init script before </body>. Only on templates (`{{ lang_code }}`
    #     placeholder present) AND tool pages (`container-narrow` layout) — the
    #     index uses a wider `.container` and would render the button next to
    #     the install button awkwardly.
    if ('{{ lang_code }}' in html and 'container-narrow' in html
            and 'data-utilify-fav-toggle' not in html):
        fav_btn_html = (
            '\n                    <button data-utilify-fav-toggle '
            'class="fav-toggle-page" type="button" '
            'aria-label="{{ fav_add_aria }}" '
            'data-add-label="{{ fav_add_aria }}" '
            'data-remove-label="{{ fav_remove_aria }}">☆</button>'
        )
        # Insert after the install button (matches both block and inline placeholder formats).
        html = _re_ad.sub(
            r'(<button id="pwaInstallBtn"[^>]*>\s*\{\{\s*install_app\s*\}\}\s*</button>)',
            lambda m: m.group(1) + fav_btn_html,
            html, count=1,
        )
        fav_init = (
            '    <script data-utilify-fav-toggle-script>(function(){'
            'var btn=document.querySelector(".fav-toggle-page");'
            'if(!btn)return;'
            'var m=location.pathname.match(/^\\/[^\\/]+\\/([^\\/]+)\\/?$/);'
            'if(!m)return;'
            'var slug=m[1],K="utilify_favorites";'
            'function g(){return (localStorage.getItem(K)||"").split(",").filter(Boolean);}'
            'function s(a){localStorage.setItem(K,Array.from(new Set(a)).join(","));}'
            'function p(f){btn.textContent=f?"★":"☆";'
            'btn.classList.toggle("is-fav",f);'
            'btn.setAttribute("aria-label",f?btn.dataset.removeLabel:btn.dataset.addLabel);'
            'btn.setAttribute("aria-pressed",String(f));}'
            'p(g().indexOf(slug)>-1);'
            'btn.addEventListener("click",function(){var a=g(),'
            'n=a.indexOf(slug)>-1?a.filter(function(x){return x!==slug;}):a.concat([slug]);'
            's(n);p(n.indexOf(slug)>-1);});})();</script>\n'
        )
        html = html.replace('</body>', fav_init + '</body>', 1)

    # 9c. Inject skip-to-content link as first child of <body>, and ensure
    #     <main> has id="main" so the skip link has a target. Idempotent
    #     via marker `data-utilify-skip`.
    if 'data-utilify-skip' not in html:
        if '{{ lang_code }}' in html:
            link_text = '{{ skip_link }}'
        else:
            link_text = 'Skip to content'
        skip = (
            f'\n    <a data-utilify-skip class="skip-link" href="#main">{link_text}</a>'
        )
        html = _re_ad.sub(r'(<body[^>]*>)', r'\1' + skip, html, count=1)
        # Ensure <main ...> has id="main"; only patch if missing.
        if '<main' in html and 'id="main"' not in html:
            html = _re_ad.sub(
                r'(<main\b)([^>]*)(>)',
                lambda m: m.group(1) + ' id="main"' + m.group(2) + m.group(3),
                html, count=1,
            )

    # 10. Inject legal-page links into footer of *templates* (those still have
    #     the {{ lang_code }} placeholder). For prebuilt hand-authored pages we
    #     inject lang-resolved links separately in sync_prebuilt_tools().
    if '{{ lang_code }}' in html and 'data-legal-links' not in html:
        legal_block = (
            '\n                <p data-legal-links style="font-size: 0.875rem; margin-top: 8px;">'
            '<a href="/{{ lang_code }}/about/">{{ link_about }}</a> · '
            '<a href="/{{ lang_code }}/privacy/">{{ link_privacy }}</a> · '
            '<a href="/{{ lang_code }}/terms/">{{ link_terms }}</a>'
            '</p>'
        )
        html = _re_ad.sub(
            r'(<p>\{\{ footer \}\}</p>)',
            r'\1' + legal_block,
            html, count=1,
        )

    return html


def inject_legal_links_resolved(html, lang):
    """Insert legal-page footer links with the language code already
    substituted. Used for prebuilt pages that arrive at sync time without
    {{ lang_code }} placeholders. Idempotent."""
    if 'data-legal-links' in html:
        return html
    common = COMMON.get('en', {}).copy()
    common.update(COMMON.get(lang, {}))
    about = common.get('link_about', 'About')
    privacy = common.get('link_privacy', 'Privacy')
    terms = common.get('link_terms', 'Terms')
    block = (
        f'\n                <p data-legal-links style="font-size: 0.875rem; margin-top: 8px;">'
        f'<a href="/{lang}/about/">{about}</a> · '
        f'<a href="/{lang}/privacy/">{privacy}</a> · '
        f'<a href="/{lang}/terms/">{terms}</a>'
        f'</p>'
    )
    # Insert before </footer>'s inner closing div.
    out = _re_ad.sub(
        r'(</div>\s*</div>\s*</footer>)',
        block + r'\n            \1',
        html, count=1,
    )
    return out
# --- end monetization ----------------------------------------------------------

# Tool category mapping for the index filter. Tools not listed default to 'convert'.
TOOL_CATEGORIES = {
    # Developer
    'json-formatter': 'dev', 'jwt-decoder': 'dev', 'hash-generator': 'dev',
    'uuid-generator': 'dev', 'base64-converter': 'dev', 'url-encoder': 'dev',
    'sql-formatter': 'dev', 'regex-tester': 'dev', 'json-to-ts': 'dev',
    'jpa-converter': 'dev', 'json-ld-generator': 'dev',
    'json-schema-validator': 'dev',
    # Text
    'text-utils': 'text', 'diff-checker': 'text', 'lorem-ipsum': 'text',
    'markdown-previewer': 'text',
    # Image
    'image-converter': 'image', 'image-watermark': 'image', 'image-editor': 'image',
    'favicon-generator': 'image', 'qr-generator': 'image', 'thumbnail-downloader': 'image',
    # Converters
    'unit-converter': 'convert', 'color-converter': 'convert',
    'unix-timestamp': 'convert', 'json-to-excel': 'convert',
    'excel-to-sql': 'convert', 'text-to-diagram': 'convert', 'pdf-tools': 'convert',
    # Calculators / misc
    'bmi-calculator': 'calc', 'date-calculator': 'calc', 'timer': 'calc',
    'reaction-test': 'calc', 'password-generator': 'calc',
    'loan-calculator': 'calc', 'compound-interest': 'calc',
    'retirement-calculator': 'calc',
    'calorie-calculator': 'calc', 'pregnancy-calculator': 'calc',
    'body-fat-calculator': 'calc',
    'tip-calculator': 'calc', 'percentage-calculator': 'calc',
    'discount-calculator': 'calc',
    # AI-era utilities
    'token-counter': 'ai', 'mcp-config-generator': 'ai',
    'ai-image-inspector': 'ai', 'chatgpt-to-blog': 'ai',
    'prompt-pii-scrubber': 'ai', 'claude-md-generator': 'ai',
    'rag-chunker': 'ai', 'few-shot-formatter': 'ai',
}

# L1 sub-categories. Tools without an entry render with an empty data-subcategory
# attribute (which the index "All" subchip matches). Currently only 'finance'
# under 'calc' is populated; future sub-categories (health, real-estate, tax,
# ai-text, etc.) plug in here without touching TOOL_CATEGORIES.
TOOL_SUBCATEGORIES = {
    'loan-calculator': 'finance',
    'compound-interest': 'finance',
    'retirement-calculator': 'finance',
    'calorie-calculator': 'health',
    'pregnancy-calculator': 'health',
    'body-fat-calculator': 'health',
}

# Map each main category to the list of sub-categories that should appear when
# that category chip is active. Order = display order. Empty list = no
# sub-chips rendered for that category.
CATEGORY_SUBCATS = {
    'calc': ['finance', 'health'],
}

# L2 hub pages — one curated landing page per sub-category. Slug = sub-category
# id; data dict provides intro / FAQ / cross-links. Build script iterates this
# dict in build_hub_pages() and renders /<lang>/<slug>/. Hubs cross-link to
# each other via the `other_hub_slug` field.
HUB_PAGES = {
    'finance': {'data': FINANCE_HUB, 'icon': '💰', 'other_hub': 'health'},
    'health':  {'data': HEALTH_HUB,  'icon': '🩺', 'other_hub': 'finance'},
}

# Search-keyword aliases per tool. Powers the index page's live search bar
# (see L3 in _templates/index.html). Entries are space-joined into the
# `data-keywords` attribute on each card; matched against the search query
# alongside the card's title and description.
TOOL_KEYWORDS = {
    'json-formatter': ['json', 'format', 'pretty', 'minify', 'validate'],
    'jwt-decoder': ['jwt', 'token', 'auth', 'jose', 'decode'],
    'base64-converter': ['base64', 'encode', 'decode', 'b64'],
    'hash-generator': ['hash', 'md5', 'sha', 'sha256', 'digest'],
    'uuid-generator': ['uuid', 'guid', 'random', 'identifier'],
    'url-encoder': ['url', 'encode', 'decode', 'percent', 'escape'],
    'unit-converter': ['unit', 'convert', 'length', 'weight', 'volume', 'temperature'],
    'color-converter': ['color', 'colour', 'hex', 'rgb', 'hsl'],
    'qr-generator': ['qr', 'qrcode', 'barcode'],
    'image-converter': ['image', 'png', 'jpg', 'webp', 'avif', 'convert'],
    'image-watermark': ['watermark', 'image', 'overlay', 'logo'],
    'favicon-generator': ['favicon', 'icon', 'apple-touch'],
    'thumbnail-downloader': ['thumbnail', 'youtube', 'download', 'image'],
    'bmi-calculator': ['bmi', 'body mass', 'weight', 'health'],
    'date-calculator': ['date', 'duration', 'between', 'days'],
    'unix-timestamp': ['unix', 'timestamp', 'epoch', 'time'],
    'timer': ['timer', 'stopwatch', 'countdown'],
    'reaction-test': ['reaction', 'reflex', 'speed'],
    'password-generator': ['password', 'random', 'secure', 'strong'],
    'sql-formatter': ['sql', 'format', 'query', 'database'],
    'lorem-ipsum': ['lorem', 'ipsum', 'placeholder', 'dummy'],
    'markdown-previewer': ['markdown', 'md', 'preview', 'render'],
    'regex-tester': ['regex', 'regular expression', 'pattern', 'match'],
    'text-utils': ['text', 'case', 'uppercase', 'lowercase', 'count'],
    'diff-checker': ['diff', 'compare', 'text', 'difference'],
    'token-counter': ['token', 'gpt', 'claude', 'cost', 'tiktoken'],
    'mcp-config-generator': ['mcp', 'claude desktop', 'cursor', 'config'],
    'ai-image-inspector': ['ai', 'image', 'metadata', 'midjourney', 'stable diffusion'],
    'chatgpt-to-blog': ['chatgpt', 'blog', 'markdown', 'export'],
    'prompt-pii-scrubber': ['pii', 'prompt', 'mask', 'redact', 'privacy'],
    'claude-md-generator': ['claude', 'claude.md', 'system prompt'],
    'loan-calculator': ['loan', 'mortgage', 'amortization', 'payment', 'interest'],
    'compound-interest': ['compound', 'interest', 'investment', 'savings'],
    'retirement-calculator': ['retirement', '401k', 'pension', 'nest egg'],
    'calorie-calculator': ['calorie', 'bmr', 'tdee', 'macro', 'diet'],
    'pregnancy-calculator': ['pregnancy', 'due date', 'lmp', 'gestation', 'trimester'],
    'body-fat-calculator': ['body fat', 'bfp', 'navy', 'composition'],
    'rag-chunker': ['rag', 'chunk', 'split', 'embedding', 'vector', 'overlap'],
    'few-shot-formatter': ['few-shot', 'prompt', 'examples', 'template', 'formatter'],
    'json-schema-validator': ['json schema', 'validate', 'ajv', 'schema', 'jsonpath'],
    'tip-calculator': ['tip', 'gratuity', 'split', 'bill', 'restaurant'],
    'percentage-calculator': ['percent', 'percentage', 'change', 'increase', 'decrease'],
    'discount-calculator': ['discount', 'sale', 'price', 'markdown', 'savings'],
    'json-to-ts': ['json', 'typescript', 'interface', 'dto'],
    'jpa-converter': ['jpa', 'entity', 'sql', 'hibernate'],
    'excel-to-sql': ['excel', 'sql', 'insert', 'csv'],
    'json-to-excel': ['json', 'excel', 'xlsx', 'spreadsheet'],
    'json-ld-generator': ['json-ld', 'schema', 'seo', 'structured'],
    'image-editor': ['image', 'crop', 'rotate', 'filter'],
    'pdf-tools': ['pdf', 'merge', 'split'],
    'text-to-diagram': ['diagram', 'flowchart', 'sequence', 'mermaid'],
}

# Slugs of the 5 tools surfaced in the "Featured" hero strip.
FEATURED_SLUGS = ['json-formatter', 'jwt-decoder', 'uuid-generator',
                  'base64-converter', 'hash-generator']

# Conversion-pair slugs surfaced in the "Popular Conversions" section,
# linking the index to /convert/* SEO pages for crawl + discovery.
POPULAR_CONVERSION_SLUGS = [
    'cm-to-inches', 'inches-to-cm',
    'kg-to-lbs', 'lbs-to-kg',
    'celsius-to-fahrenheit', 'fahrenheit-to-celsius',
    'miles-to-km', 'km-to-miles',
    'meters-to-feet', 'feet-to-meters',
]


def build_index_page():
    print("Building index pages...")
    template = load_template('index.html')

    # Build a lookup for tool dicts (TOOLS_CONFIG + PREBUILT_TOOLS).
    tool_lookup = {tool_path: tool_dict for tool_path, _icon, tool_dict in ALL_TOOLS}
    icon_lookup = {tool_path: icon for tool_path, icon, _td in ALL_TOOLS}

    # Conversion pair display names (en/ko fall back to en for other locales).
    try:
        from _data.conversions import CONVERSION_PAIRS
    except ImportError:
        CONVERSION_PAIRS = []
    pair_lookup = {f"{p['from']}-to-{p['to']}": p for p in CONVERSION_PAIRS}

    for lang in LANGUAGES:
        # Prepare data: English fallback for any missing sub-keys
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(INDEX_PAGE.get('en', {}))
        data.update(INDEX_PAGE.get(lang, {}))
        data['lang_code'] = lang

        # Generate alternate links
        alt_links = []
        for l in LANGUAGES:
            if l == 'zh-cn':
                hreflang = 'zh-Hans'
            elif l == 'zh-tw':
                hreflang = 'zh-Hant'
            else:
                hreflang = l
            alt_links.append(f'<link rel="alternate" hreflang="{hreflang}" href="https://utilifyapp.net/{l}/">')

        alt_links.append('<link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/">')
        data['alternate_links'] = '\n  '.join(alt_links)

        # Featured cards (5 high-traffic tools).
        featured_html = []
        for slug in FEATURED_SLUGS:
            tool_dict = tool_lookup.get(slug)
            if not tool_dict:
                continue
            t_data = tool_dict.get(lang, tool_dict.get('en', {}))
            title = t_data.get('title') or tool_dict['en']['title']
            desc = t_data.get('page_desc') or t_data.get('meta_desc') \
                or tool_dict['en'].get('page_desc', tool_dict['en'].get('meta_desc', ''))
            icon = icon_lookup.get(slug, '🛠️')
            featured_html.append(
                f'<a href="/{lang}/{slug}/" class="featured-card">'
                f'<div class="card-icon">{icon}</div>'
                f'<h3 class="card-title">{title}</h3>'
                f'<p class="card-description">{desc}</p></a>'
            )
        data['featured_cards'] = '\n          '.join(featured_html)

        # Generate tool cards with data-category + data-subcategory for filters,
        # plus a favorites-toggle button (★) wired up by the index JS.
        fav_add_aria = data.get('fav_add_aria', 'Add to favorites')
        fav_remove_aria = data.get('fav_remove_aria', 'Remove from favorites')
        cards_html = []
        for tool_path, icon, tool_dict in ALL_TOOLS:
            t_data = tool_dict.get(lang, tool_dict.get('en', {}))
            title = t_data.get('title', tool_dict.get('en', {}).get('title', ''))
            desc = t_data.get('page_desc', t_data.get('meta_desc', ''))
            if not title:
                title = tool_dict['en']['title']
            if not desc:
                desc = tool_dict['en'].get('page_desc', tool_dict['en'].get('meta_desc', ''))
            cat = TOOL_CATEGORIES.get(tool_path, 'convert')
            sub = TOOL_SUBCATEGORIES.get(tool_path, '')
            keywords = ' '.join(TOOL_KEYWORDS.get(tool_path, []))
            card = f'''
        <a href="/{lang}/{tool_path}/" class="card" data-category="{cat}" data-subcategory="{sub}" data-slug="{tool_path}" data-keywords="{keywords}">
          <button type="button" class="fav-toggle" data-fav="{tool_path}" aria-label="{fav_add_aria}" data-add-label="{fav_add_aria}" data-remove-label="{fav_remove_aria}">☆</button>
          <div class="card-icon">{icon}</div>
          <h3 class="card-title">{title}</h3>
          <p class="card-description">{desc}</p>
        </a>'''
            cards_html.append(card)
        data['tool_cards'] = '\n'.join(cards_html)

        # Build subcategory chip groups for any main category that has sub-categories.
        # Sub-categories that also have a hub page (`HUB_PAGES`) get a "→ <hub>"
        # text link rendered next to the chip, hidden until that subcat is active.
        subcat_html = []
        for main_cat, subs in CATEGORY_SUBCATS.items():
            chips = [
                f'<button type="button" class="subcat-chip" data-subcat="" aria-pressed="true">{data.get("subcat_all", "All")}</button>'
            ]
            for sub in subs:
                label = data.get(f'subcat_{sub}', sub.title())
                chips.append(
                    f'<button type="button" class="subcat-chip" data-subcat="{sub}" aria-pressed="false">{label}</button>'
                )
                if sub in HUB_PAGES:
                    hub_label = data.get(f'hub_link_{sub}', f'{sub.title()} hub')
                    chips.append(
                        f'<a href="/{lang}/{sub}/" class="hub-link" '
                        f'data-for-subcat="{sub}" hidden>→ {hub_label}</a>'
                    )
            subcat_html.append(
                f'<div class="subcat-chips" data-parent-cat="{main_cat}" role="group" '
                f'aria-label="{data.get("subcat_filter_aria", "Subcategory filter")}" hidden>'
                + ''.join(chips) +
                '</div>'
            )
        data['subcategory_chips'] = '\n            '.join(subcat_html)

        # Popular Conversions text-link grid.
        popular_html = []
        for pair_slug in POPULAR_CONVERSION_SLUGS:
            p = pair_lookup.get(pair_slug)
            if not p:
                continue
            from_long = p['from_long'].get(lang, p['from_long']['en'])
            to_long = p['to_long'].get(lang, p['to_long']['en'])
            if lang != 'ko':
                from_long, to_long = from_long.title(), to_long.title()
            popular_html.append(
                f'<a href="/{lang}/convert/{pair_slug}/" class="popular-conv-link">'
                f'{from_long} → {to_long}</a>'
            )
        data['popular_conversions'] = '\n          '.join(popular_html)

        # Replace placeholders
        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))

        # Write
        output_dir = os.path.join(BASE_DIR, lang)
        os.makedirs(output_dir, exist_ok=True)
        with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"  Generated {lang}/index.html")

def build_conversion_pages():
    """Programmatic SEO: render `_templates/convert_pair.html` for every
    (pair × language) combination, producing /<lang>/convert/<from>-to-<to>/."""
    print("Building conversion pages...")
    template = load_template('convert_pair.html')
    if template is None:
        return

    from _data.conversions import (
        CONVERSION_PAIRS, TABLE_INPUT_VALUES, TABLE_INPUT_VALUES_TEMP,
        convert as py_convert, format_number,
    )
    import json as _json

    same_type = {}
    for p in CONVERSION_PAIRS:
        same_type.setdefault(p['type'], []).append(p)

    for pair in CONVERSION_PAIRS:
        slug = f"{pair['from']}-to-{pair['to']}"
        url_path = f"convert/{slug}"
        alt_links_html = build_alt_links(url_path)

        is_temp = pair['type'] == 'temperature'
        inputs = TABLE_INPUT_VALUES_TEMP if is_temp else TABLE_INPUT_VALUES

        # Pre-compute table at build time for SEO content.
        table_rows = []
        for v in inputs:
            result = py_convert(v, pair['mode'], pair.get('factor'))
            table_rows.append(
                f"<tr><td>{format_number(v, 0)}</td>"
                f"<td>{format_number(result, pair['precision'])}</td></tr>"
            )
        table_rows_html = '\n                    '.join(table_rows)

        for lang in LANGUAGES:
            data = COMMON.get('en', {}).copy()
            data.update(COMMON.get(lang, {}))
            data['lang_code'] = lang
            data['pair_slug'] = slug
            data['alternate_links'] = alt_links_html

            from_long = pair['from_long'].get(lang, pair['from_long']['en'])
            to_long = pair['to_long'].get(lang, pair['to_long']['en'])

            if lang == 'ko':
                data['h1_text'] = f"{from_long} → {to_long} 변환기"
                data['intro_text'] = (
                    f"{from_long}({pair['from']})를 {to_long}({pair['to']})로 빠르게 변환하세요. "
                    f"입력값은 브라우저에서만 처리됩니다."
                )
                data['formula_label'] = "공식:"
                data['table_title'] = "변환 표"
                data['faq_title'] = "자주 묻는 질문"
                data['related_header'] = "관련 도구"
                data['related_main'] = "전체 단위 변환기"
                data['meta_title'] = f"{from_long} → {to_long} 변환기 - Utilify"
                data['meta_desc'] = (
                    f"{pair['from']}를 {pair['to']}로 변환하는 무료 온라인 도구. "
                    f"공식, 변환 표, 즉시 계산. 모든 처리는 브라우저에서 수행됩니다."
                )
            else:
                data['h1_text'] = f"{from_long.title()} to {to_long.title()} Converter"
                data['intro_text'] = (
                    f"Convert {from_long} ({pair['from']}) to {to_long} ({pair['to']}) instantly. "
                    f"All calculations run in your browser."
                )
                data['formula_label'] = "Formula:"
                data['table_title'] = "Conversion Table"
                data['faq_title'] = "Frequently Asked Questions"
                data['related_header'] = "Related Tools"
                data['related_main'] = "Full Unit Converter"
                data['meta_title'] = f"{from_long.title()} to {to_long.title()} Converter (Free Online) - Utilify"
                data['meta_desc'] = (
                    f"Convert {pair['from']} to {pair['to']} online — free, no signup, no upload. "
                    f"Formula, conversion table, instant results. {pair['formula']}."
                )

            data['from_long'] = from_long.title() if lang != 'ko' else from_long
            data['to_long'] = to_long.title() if lang != 'ko' else to_long
            data['formula'] = pair['formula']
            data['mode'] = pair['mode']
            data['factor_js'] = repr(pair.get('factor', 0)) if pair['mode'] == 'linear' else '0'
            data['precision'] = pair['precision']
            data['table_rows_html'] = table_rows_html

            # FAQ content (en/ko only; others fall back to en).
            one_to_target = py_convert(1, pair['mode'], pair.get('factor'))
            one_to_target_str = format_number(one_to_target, pair['precision'])
            ten_to_target_str = format_number(py_convert(10, pair['mode'], pair.get('factor')), pair['precision'])

            if lang == 'ko':
                faqs = [
                    (
                        f"1 {pair['from']}는 몇 {pair['to']}인가요?",
                        f"1 {pair['from']} = {one_to_target_str} {pair['to']} 입니다. {pair['formula']}",
                    ),
                    (
                        f"{pair['from']}를 {pair['to']}로 변환하는 공식은?",
                        f"{pair['formula']}. 역변환: {pair['inverse_formula']}.",
                    ),
                    (
                        f"10 {pair['from']}는 몇 {pair['to']}인가요?",
                        f"10 {pair['from']} = {ten_to_target_str} {pair['to']} 입니다.",
                    ),
                    (
                        f"이 변환은 정확한가요?",
                        f"네, 표준 정의에 따른 정확한 변환 계수를 사용합니다 (소수점 {pair['precision']}자리까지 표시).",
                    ),
                ]
            else:
                faqs = [
                    (
                        f"How many {pair['to']} are in 1 {pair['from']}?",
                        f"1 {pair['from']} equals {one_to_target_str} {pair['to']}. {pair['formula']}",
                    ),
                    (
                        f"What is the formula to convert {pair['from']} to {pair['to']}?",
                        f"{pair['formula']}. Inverse: {pair['inverse_formula']}.",
                    ),
                    (
                        f"How many {pair['to']} are in 10 {pair['from']}?",
                        f"10 {pair['from']} equals {ten_to_target_str} {pair['to']}.",
                    ),
                    (
                        f"Is this conversion exact?",
                        f"Yes, the converter uses the standard definition factor and rounds the displayed result to {pair['precision']} decimal places.",
                    ),
                ]

            faq_html_parts = [
                f'<details class="faq" open><summary>{q}</summary><p>{a}</p></details>'
                for q, a in faqs
            ]
            data['faq_html'] = '\n            '.join(faq_html_parts)

            faq_jsonld = {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {"@type": "Question", "name": q,
                     "acceptedAnswer": {"@type": "Answer", "text": a}}
                    for q, a in faqs
                ],
            }
            data['faq_jsonld'] = _json.dumps(faq_jsonld, ensure_ascii=False, indent=2)

            related = []
            for other in same_type[pair['type']]:
                if other is pair:
                    continue
                other_from = other['from_long'].get(lang, other['from_long']['en'])
                other_to = other['to_long'].get(lang, other['to_long']['en'])
                arrow = " → "
                related.append(
                    f'<a href="/{lang}/convert/{other["from"]}-to-{other["to"]}/" class="related-btn">'
                    f'{other_from.title() if lang != "ko" else other_from}{arrow}'
                    f'{other_to.title() if lang != "ko" else other_to}</a>'
                )
            data['related_pairs_html'] = ''.join(related)

            content = template
            for key, value in data.items():
                content = content.replace(f'{{{{ {key} }}}}', str(value))

            output_dir = os.path.join(BASE_DIR, lang, 'convert', slug)
            os.makedirs(output_dir, exist_ok=True)
            with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
                f.write(content)
        print(f"  Generated convert/{slug}/ for {len(LANGUAGES)} languages")


def build_static_page(slug, page_data, root_404=False):
    """Render `_templates/static_page.html` for each language to /<lang>/<slug>/.
    If root_404 is True, also write the English version to /404.html so GitHub
    Pages serves it for unknown URLs."""
    print(f"Building static page: {slug}...")
    template = load_template('static_page.html')
    if template is None:
        return

    alt_links_html = build_alt_links(slug)

    for lang in LANGUAGES:
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(page_data.get('en', {}))
        data.update(page_data.get(lang, {}))
        data['lang_code'] = lang
        data['page_slug'] = slug
        data['alternate_links'] = alt_links_html

        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))

        output_dir = os.path.join(BASE_DIR, lang, slug)
        os.makedirs(output_dir, exist_ok=True)
        with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  Generated {lang}/{slug}/index.html")

    if root_404:
        # Render an English copy at /404.html so GitHub Pages serves it on misses.
        data = COMMON.get('en', {}).copy()
        data.update(page_data.get('en', {}))
        data['lang_code'] = 'en'
        data['page_slug'] = slug
        data['alternate_links'] = alt_links_html
        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))
        with open(os.path.join(BASE_DIR, '404.html'), 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  Generated /404.html")


def build_hub_pages():
    """Render `_templates/category_hub.html` for each entry in HUB_PAGES,
    once per language. Each hub is a curated landing page that lists the tools
    mapped to its sub-category in TOOL_SUBCATEGORIES, plus intro copy and FAQs.
    Mirrors build_conversion_pages() in shape — one template × N pages.

    Also emits FAQPage + BreadcrumbList JSON-LD parsed from the rendered FAQ
    HTML so hubs are eligible for Google rich-snippet treatment. The visible
    breadcrumb in the template uses the same data."""
    print("Building category hub pages...")
    import json as _json_hub
    import re as _re_hub
    template = load_template('category_hub.html')
    if template is None:
        return

    faq_pat = _re_hub.compile(
        r'<details>\s*<summary>(.*?)</summary>\s*(.*?)</details>',
        _re_hub.DOTALL,
    )
    tag_pat = _re_hub.compile(r'<[^>]+>')

    for hub_slug, hub_meta in HUB_PAGES.items():
        hub_data = hub_meta['data']
        hub_icon = hub_meta['icon']
        other_hub = hub_meta['other_hub']

        # Tools that belong to this hub via TOOL_SUBCATEGORIES.
        tools_in_hub = [
            (t_path, icon, t_dict)
            for t_path, icon, t_dict in ALL_TOOLS
            if TOOL_SUBCATEGORIES.get(t_path) == hub_slug
        ]
        alt_links_html = build_alt_links(hub_slug)

        for lang in LANGUAGES:
            data = COMMON.get('en', {}).copy()
            data.update(COMMON.get(lang, {}))
            data.update(hub_data.get('en', {}))
            data.update(hub_data.get(lang, {}))
            data['lang_code'] = lang
            data['hub_slug'] = hub_slug
            data['hub_icon'] = hub_icon
            data['other_hub_slug'] = other_hub
            data['alternate_links'] = alt_links_html

            cards = []
            for t_path, icon, t_dict in tools_in_hub:
                t_data = t_dict.get(lang, t_dict.get('en', {}))
                title = t_data.get('title') or t_dict['en'].get('title', '')
                desc = (t_data.get('card_blurb')
                        or t_data.get('page_desc')
                        or t_data.get('meta_desc')
                        or t_dict['en'].get('card_blurb', t_dict['en'].get('page_desc', '')))
                cards.append(
                    f'<a href="/{lang}/{t_path}/" class="card hub-card" data-slug="{t_path}">'
                    f'<div class="card-icon">{icon}</div>'
                    f'<h3 class="card-title">{title}</h3>'
                    f'<p class="card-description">{desc}</p>'
                    f'</a>'
                )
            data['tool_cards_html'] = '\n                '.join(cards)

            # BreadcrumbList JSON-LD: Home > Hub.
            breadcrumb_schema = {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": data.get('breadcrumb_home', 'Home'),
                        "item": f"https://utilifyapp.net/{lang}/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": data.get('h1', hub_slug.title()),
                        "item": f"https://utilifyapp.net/{lang}/{hub_slug}/",
                    },
                ],
            }
            data['breadcrumb_schema'] = _json_hub.dumps(
                breadcrumb_schema, ensure_ascii=False, indent=2,
            )

            # FAQPage JSON-LD parsed from the rendered FAQ HTML (the same
            # source the template renders into the visible <details> blocks).
            faq_pairs = faq_pat.findall(data.get('faq_html', '') or '')
            faq_schema = {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": tag_pat.sub('', q).strip(),
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": tag_pat.sub('', a).strip(),
                        },
                    }
                    for q, a in faq_pairs
                ],
            }
            data['faq_schema'] = _json_hub.dumps(
                faq_schema, ensure_ascii=False, indent=2,
            )

            content = template
            for key, value in data.items():
                content = content.replace(f'{{{{ {key} }}}}', str(value))

            output_dir = os.path.join(BASE_DIR, lang, hub_slug)
            os.makedirs(output_dir, exist_ok=True)
            with open(os.path.join(output_dir, 'index.html'), 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  Generated {lang}/{hub_slug}/index.html")


def build_alt_links(tool_path):
    alt = []
    for l in LANGUAGES:
        if l == 'zh-cn':
            hreflang = 'zh-Hans'
        elif l == 'zh-tw':
            hreflang = 'zh-Hant'
        else:
            hreflang = l
        alt.append(f'<link rel="alternate" hreflang="{hreflang}" href="https://utilifyapp.net/{l}/{tool_path}/">')
    alt.append(f'<link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/{tool_path}/">')
    return '\n    '.join(alt)


def build_tool(tool_name, tool_data, template_file):
    print(f"Building {tool_name}...")
    template = load_template(template_file)
    if template is None:
        return

    alt_links_html = build_alt_links(tool_name)

    for lang in LANGUAGES:
        # Merge common and specific data with English as fallback for missing sub-keys
        data = COMMON.get('en', {}).copy()
        data.update(COMMON.get(lang, {}))
        data.update(tool_data.get('en', {}))
        data.update(tool_data.get(lang, {}))
        data['lang_code'] = lang
        data['alternate_links'] = alt_links_html

        # Replace placeholders
        content = template
        for key, value in data.items():
            content = content.replace(f'{{{{ {key} }}}}', str(value))
            
        # Write to file
        output_dir = os.path.join(BASE_DIR, lang, tool_name)
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, 'index.html')
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"  Generated {lang}/{tool_name}/index.html")


def hreflang_for(lang):
    if lang == 'zh-cn':
        return 'zh-Hans'
    if lang == 'zh-tw':
        return 'zh-Hant'
    return lang


def build_sitemap(today=None):
    print("Building sitemap.xml...")
    from datetime import date
    lastmod = (today or date.today()).isoformat()

    # High-traffic developer tools — get higher priority + monthly changefreq.
    POPULAR_TOOLS = {
        'json-formatter', 'base64-converter', 'jwt-decoder', 'uuid-generator',
        'hash-generator', 'unix-timestamp', 'url-encoder',
    }

    paths = ['']  # root
    paths += [f'{l}/' for l in LANGUAGES]
    for tool_path, _icon, _data in ALL_TOOLS:
        for l in LANGUAGES:
            paths.append(f'{l}/{tool_path}/')

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
             '        xmlns:xhtml="http://www.w3.org/1999/xhtml">']

    def emit(loc, alternates=None, priority='0.5', changefreq='monthly'):
        lines.append('  <url>')
        lines.append(f'    <loc>{loc}</loc>')
        lines.append(f'    <lastmod>{lastmod}</lastmod>')
        lines.append(f'    <changefreq>{changefreq}</changefreq>')
        lines.append(f'    <priority>{priority}</priority>')
        if alternates:
            for hl, href in alternates:
                lines.append(f'    <xhtml:link rel="alternate" hreflang="{hl}" href="{href}"/>')
        lines.append('  </url>')

    # Root
    emit('https://utilifyapp.net/', priority='1.0', changefreq='weekly')

    # Language home pages with hreflang siblings
    home_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/') for l in LANGUAGES]
    home_alts.append(('x-default', 'https://utilifyapp.net/en/'))
    for l in LANGUAGES:
        emit(f'https://utilifyapp.net/{l}/', home_alts, priority='0.9', changefreq='weekly')

    # Tool pages with hreflang siblings
    for tool_path, _icon, _data in ALL_TOOLS:
        tool_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{tool_path}/') for l in LANGUAGES]
        tool_alts.append(('x-default', f'https://utilifyapp.net/en/{tool_path}/'))
        priority = '0.8' if tool_path in POPULAR_TOOLS else '0.7'
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{tool_path}/', tool_alts, priority=priority, changefreq='monthly')

    # Static / legal pages
    for slug in STATIC_PAGE_SLUGS:
        slug_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{slug}/') for l in LANGUAGES]
        slug_alts.append(('x-default', f'https://utilifyapp.net/en/{slug}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{slug}/', slug_alts, priority='0.3', changefreq='yearly')
        paths.extend([f'{l}/{slug}/' for l in LANGUAGES])

    # Category hub pages — between conversion pages and tool pages in priority.
    for hub_slug in HUB_PAGES:
        hub_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{hub_slug}/') for l in LANGUAGES]
        hub_alts.append(('x-default', f'https://utilifyapp.net/en/{hub_slug}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{hub_slug}/', hub_alts, priority='0.6', changefreq='monthly')
        paths.extend([f'{l}/{hub_slug}/' for l in LANGUAGES])

    # Programmatic SEO conversion pairs
    try:
        from _data.conversions import CONVERSION_PAIRS
    except ImportError:
        CONVERSION_PAIRS = []
    for pair in CONVERSION_PAIRS:
        slug = f"convert/{pair['from']}-to-{pair['to']}"
        pair_alts = [(hreflang_for(l), f'https://utilifyapp.net/{l}/{slug}/') for l in LANGUAGES]
        pair_alts.append(('x-default', f'https://utilifyapp.net/en/{slug}/'))
        for l in LANGUAGES:
            emit(f'https://utilifyapp.net/{l}/{slug}/', pair_alts, priority='0.6', changefreq='monthly')
        paths.extend([f'{l}/{slug}/' for l in LANGUAGES])

    lines.append('</urlset>')
    out = os.path.join(BASE_DIR, 'sitemap.xml')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Generated sitemap.xml ({len(paths)} urls)")


STATIC_PAGE_SLUGS = ['about', 'privacy', 'terms']


PREBUILT_LANGS_AUTHORED = ['en', 'ko', 'ja', 'de', 'hi', 'id', 'pt', 'th', 'vi']
PREBUILT_LANGS_CLONED = ['zh-cn', 'zh-tw']

# Block of <link rel="alternate" ...> entries for hand-authored prebuilt tool
# pages. We replace whatever the page currently has between the "<!-- Language
# Alternatives -->" marker and the next blank line, so old 9-language blocks
# get refreshed to include zh-cn / zh-tw.
import re as _re


def _build_prebuilt_alternates(tool_path: str) -> str:
    lines = ['  <!-- Language Alternatives -->']
    for l in LANGUAGES:
        hl = hreflang_for(l)
        lines.append(f'  <link rel="alternate" hreflang="{hl}" href="https://utilifyapp.net/{l}/{tool_path}/">')
    lines.append(f'  <link rel="alternate" hreflang="x-default" href="https://utilifyapp.net/en/{tool_path}/">')
    return '\n'.join(lines)


def _refresh_alternates(html: str, tool_path: str) -> str:
    block = _build_prebuilt_alternates(tool_path)
    pattern = _re.compile(
        r'[ \t]*<!--\s*Language Alternatives\s*-->\s*\n'
        r'(?:[ \t]*<link\s+rel="alternate"[^>]*>\s*\n)+',
        _re.IGNORECASE,
    )
    if pattern.search(html):
        return pattern.sub(block + '\n', html, count=1)
    # No existing block — insert before </head>.
    return html.replace('</head>', block + '\n</head>', 1)


def _retarget_lang(html: str, tool_path: str, dst_lang: str) -> str:
    """Convert an English-locale HTML page into another locale by rewriting
    the `lang` attribute, JSON-LD `inLanguage`, and the canonical/og:url for
    /en/<tool>/. Only the *self* URL is rewritten — alternate links are
    regenerated separately via _refresh_alternates."""
    out = html.replace('<html lang="en">', f'<html lang="{dst_lang}">', 1)
    out = out.replace('"inLanguage": "en"', f'"inLanguage": "{dst_lang}"')
    out = out.replace(
        f'href="https://utilifyapp.net/en/{tool_path}/"',
        f'href="https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    out = out.replace(
        f'content="https://utilifyapp.net/en/{tool_path}/"',
        f'content="https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    out = out.replace(
        f'"url": "https://utilifyapp.net/en/{tool_path}/"',
        f'"url": "https://utilifyapp.net/{dst_lang}/{tool_path}/"',
    )
    # Header logo link.
    out = out.replace(f'href="/en/"', f'href="/{dst_lang}/"')
    return out


def sync_prebuilt_tools():
    print("Syncing prebuilt tool pages (hreflang refresh + zh-cn/zh-tw clones)...")
    for tool_path, _icon, _tool_dict in PREBUILT_TOOLS:
        # Refresh authored language pages so they include zh-cn / zh-tw alternates.
        for lang in PREBUILT_LANGS_AUTHORED:
            page = os.path.join(BASE_DIR, lang, tool_path, 'index.html')
            if not os.path.exists(page):
                continue
            with open(page, 'r', encoding='utf-8') as f:
                content = f.read()
            new_content = _refresh_alternates(content, tool_path)
            new_content = inject_monetization(new_content)
            new_content = inject_legal_links_resolved(new_content, lang)
            if new_content != content:
                with open(page, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"  refreshed {lang}/{tool_path}/index.html")

        # Clone the English page into zh-cn / zh-tw so those locales link to a
        # page rather than 404. The clone is a one-shot fallback — we only
        # write it if no page exists, so a future hand-translated version is
        # not overwritten.
        en_page = os.path.join(BASE_DIR, 'en', tool_path, 'index.html')
        if not os.path.exists(en_page):
            print(f"  WARN: missing en/{tool_path}/index.html, skipping clones")
            continue
        with open(en_page, 'r', encoding='utf-8') as f:
            en_content = f.read()
        for clone_lang in PREBUILT_LANGS_CLONED:
            clone_dir = os.path.join(BASE_DIR, clone_lang, tool_path)
            clone_path = os.path.join(clone_dir, 'index.html')
            if os.path.exists(clone_path):
                # Existing clone: still refresh hreflang + monetization so prior
                # builds don't keep stale AdSense scripts.
                with open(clone_path, 'r', encoding='utf-8') as f:
                    existing = f.read()
                refreshed = _refresh_alternates(existing, tool_path)
                refreshed = inject_monetization(refreshed)
                refreshed = inject_legal_links_resolved(refreshed, clone_lang)
                if refreshed != existing:
                    with open(clone_path, 'w', encoding='utf-8') as f:
                        f.write(refreshed)
                    print(f"  refreshed clone {clone_lang}/{tool_path}/index.html")
                continue
            retargeted = _retarget_lang(en_content, tool_path, clone_lang)
            retargeted = _refresh_alternates(retargeted, tool_path)
            retargeted = inject_monetization(retargeted)
            retargeted = inject_legal_links_resolved(retargeted, clone_lang)
            os.makedirs(clone_dir, exist_ok=True)
            with open(clone_path, 'w', encoding='utf-8') as f:
                f.write(retargeted)
            print(f"  cloned en/{tool_path}/ → {clone_lang}/{tool_path}/")


if __name__ == '__main__':
    # Build Index Pages
    build_index_page()

    # Build Tool Pages
    build_tool('sql-formatter', SQL_FORMATTER, 'sql-formatter.html')
    build_tool('json-formatter', JSON_FORMATTER, 'json-formatter.html')
    build_tool('base64-converter', BASE64_CONVERTER, 'base64-converter.html')
    build_tool('password-generator', PASSWORD_GENERATOR, 'password-generator.html')
    build_tool('unit-converter', UNIT_CONVERTER, 'unit-converter.html')
    build_tool('diff-checker', DIFF_CHECKER, 'diff-checker.html')
    build_tool('image-converter', IMAGE_CONVERTER, 'image-converter.html')
    build_tool('qr-generator', QR_GENERATOR, 'qr-generator.html')
    build_tool('color-converter', COLOR_CONVERTER, 'color-converter.html')
    build_tool('lorem-ipsum', LOREM_IPSUM, 'lorem-ipsum.html')
    build_tool('markdown-previewer', MARKDOWN_PREVIEWER, 'markdown-previewer.html')
    build_tool('regex-tester', REGEX_TESTER, 'regex-tester.html')
    build_tool('text-utils', TEXT_UTILS, 'text-utils.html')
    build_tool('bmi-calculator', BMI_CALCULATOR, 'bmi-calculator.html')
    build_tool('date-calculator', DATE_CALCULATOR, 'date-calculator.html')
    build_tool('timer', TIMER, 'timer.html')
    build_tool('image-watermark', IMAGE_WATERMARK, 'image-watermark.html')
    build_tool('favicon-generator', FAVICON_GENERATOR, 'favicon-generator.html')
    build_tool('thumbnail-downloader', THUMBNAIL_DOWNLOADER, 'thumbnail-downloader.html')
    build_tool('reaction-test', REACTION_TEST, 'reaction-test.html')
    build_tool('jwt-decoder', JWT_DECODER, 'jwt-decoder.html')
    build_tool('hash-generator', HASH_GENERATOR, 'hash-generator.html')
    build_tool('unix-timestamp', UNIX_TIMESTAMP, 'unix-timestamp.html')
    build_tool('uuid-generator', UUID_GENERATOR, 'uuid-generator.html')
    build_tool('url-encoder', URL_ENCODER, 'url-encoder.html')
    # AI-era utilities
    build_tool('token-counter', TOKEN_COUNTER, 'token-counter.html')
    build_tool('mcp-config-generator', MCP_CONFIG_GEN, 'mcp-config-generator.html')
    build_tool('ai-image-inspector', AI_IMAGE_INSPECTOR, 'ai-image-inspector.html')
    build_tool('chatgpt-to-blog', CHATGPT_TO_BLOG, 'chatgpt-to-blog.html')
    build_tool('prompt-pii-scrubber', PROMPT_PII_SCRUBBER, 'prompt-pii-scrubber.html')
    build_tool('claude-md-generator', CLAUDE_MD_GEN, 'claude-md-generator.html')
    # Finance calculators
    build_tool('loan-calculator', LOAN_CALCULATOR, 'loan-calculator.html')
    build_tool('compound-interest', COMPOUND_INTEREST, 'compound-interest.html')
    build_tool('retirement-calculator', RETIREMENT_CALCULATOR, 'retirement-calculator.html')
    # Health calculators
    build_tool('calorie-calculator', CALORIE_CALCULATOR, 'calorie-calculator.html')
    build_tool('pregnancy-calculator', PREGNANCY_CALCULATOR, 'pregnancy-calculator.html')
    build_tool('body-fat-calculator', BODY_FAT_CALCULATOR, 'body-fat-calculator.html')
    # AI / prompt-engineering tools (Tier 3)
    build_tool('rag-chunker', RAG_CHUNKER, 'rag-chunker.html')
    build_tool('few-shot-formatter', FEW_SHOT_FORMATTER, 'few-shot-formatter.html')
    build_tool('json-schema-validator', JSON_SCHEMA_VALIDATOR, 'json-schema-validator.html')
    # General-purpose calculators (high search volume)
    build_tool('tip-calculator', TIP_CALCULATOR, 'tip-calculator.html')
    build_tool('percentage-calculator', PERCENTAGE_CALCULATOR, 'percentage-calculator.html')
    build_tool('discount-calculator', DISCOUNT_CALCULATOR, 'discount-calculator.html')

    # Static / legal / 404 pages.
    build_static_page('about', ABOUT)
    build_static_page('privacy', PRIVACY)
    build_static_page('terms', TERMS)
    build_static_page('404', NOT_FOUND, root_404=True)

    # Programmatic SEO conversion pages.
    build_conversion_pages()

    # L2 category hub pages (e.g. /<lang>/finance/, /<lang>/health/).
    build_hub_pages()

    # Sync hand-authored prebuilt tools (refresh hreflang block, clone to zh-cn/zh-tw).
    sync_prebuilt_tools()

    # Build sitemap.xml
    build_sitemap()

    print("Build complete!")
